-- Database di VENDITA PRODOTTI FARMACEUTICI

-- Creazione delle tabelle
CREATE TABLE categoria (
    ID_categoria	INT AUTO_INCREMENT,
    nomeCategoria	VARCHAR(512),
    descrizione	    VARCHAR(512),
    PRIMARY KEY (ID_categoria)
);

CREATE TABLE cliente (
    ID_cliente	        INT AUTO_INCREMENT,
    nomeCliente	        VARCHAR(512),
    cognomeCliente	    VARCHAR(512),
    cfCliente	        VARCHAR(512),
    indirizzoCliente	VARCHAR(512),
    telCliente	        VARCHAR(512),
    emailCliente	    VARCHAR(512),
    PRIMARY KEY (ID_cliente)
);

CREATE TABLE fornitore (
    ID_fornitore	    INT AUTO_INCREMENT,
    nomeFornitore	    VARCHAR(512),
    indirizzoFornitore	VARCHAR(512),
    emailFornitore	    VARCHAR(512),
    telFornitore	    DOUBLE,
    PRIMARY KEY (ID_fornitore)
);

CREATE TABLE prodotto (
    ID_prodotto	    INT AUTO_INCREMENT,
    nomeProdotto    VARCHAR(512),
    pesoGrammi      INT,
    prezzo          FLOAT,
    id_categoria    INT,
    id_fornitore    INT,
  	PRIMARY KEY (ID_prodotto),
  	FOREIGN KEY (id_categoria) REFERENCES categoria(ID_categoria),
  	FOREIGN KEY (id_fornitore) REFERENCES fornitore(ID_fornitore)
);

CREATE TABLE ordine (
    ID_ordine	INT AUTO_INCREMENT,
    dataOrdine	DATE,
    id_cliente	INT,
    PRIMARY KEY (ID_ordine),
    FOREIGN KEY (id_cliente) REFERENCES cliente(ID_cliente)
);

CREATE TABLE dettOrdine (
    id_ordine	    INT,
    id_prodotto	    INT,
    quantitaProd	INT,
    FOREIGN KEY (id_ordine)	    REFERENCES ordine(ID_ordine),
    FOREIGN KEY (id_prodotto)	REFERENCES prodotto(ID_prodotto),
    PRIMARY KEY (id_ordine, id_prodotto) -- questa è una chiave primaria COMPOSTA 
);

-- Dump dei dati - tabella categoria
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Analgesici', 'Farmaci utilizzati per alleviare il dolore');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antibiotici', 'Farmaci che combattono le infezioni batteriche');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antivirali', 'Farmaci utilizzati per trattare infezioni virali');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antinfiammatori', 'Farmaci che riducono l''infiammazione');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antidepressivi', 'Farmaci utilizzati per trattare i disturbi dell''umore');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antipertensivi', 'Farmaci utilizzati per controllare la pressione sanguigna');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Antistaminici', 'Farmaci che alleviano le allergie e i sintomi associati');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Sedativi e ansiolitici', 'Farmaci utilizzati per ridurre l''ansia e favorire il sonno');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Diuretici', 'Farmaci che aumentano l''urina per ridurre la ritenzione di liquidi');
INSERT INTO categoria (nomeCategoria, descrizione) VALUES ('Anticoagulanti', 'Farmaci che prevengono la formazione di coaguli di sangue');

-- Dump dei dati - tabella cliente
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Marco', 'Rossi', 'RSSMRC85H12H501Z', 'Via Roma 92, 20100 Milano', '3351234567', 'marco.rossi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Lucia', 'Bianchi', 'BNCUCA90D60F205B', 'Corso Vittorio 9, 10100 Torino', '3399876543', 'lucia.bianchi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Alessandro', 'Verdi', 'VRDLSN82S03F839D', 'Via Napoli 26, 50100 Firenze', '3462345678', 'alessandro.verdi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Sara', 'Gallo', 'GLLSRA95A55B354F', 'Viale Bologna 175, 16100 Genova', '3387654321', 'sara.gallo@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Luca', 'Ferrari', 'FRRLCU88P30H704W', 'Via Milano 183, 70100 Bari', '3341239876', 'luca.ferrari@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Anna', 'Conti', 'CNTNNA92E65A123J', 'Piazza dei Signori 28, 35100 Verona', '3354567890', 'anna.conti@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Matteo', 'Marconi', 'MCNMTT79L14D612X', 'Via della Libertà 186, 95100 Catania', '3398761234', 'matteo.marconi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Chiara', 'Martini', 'MRTCHR91T42H501C', 'Corso Italia 89, 72100 Brindisi', '3476543210', 'chiara.martini@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Giovanni', 'Ruggeri', 'RGGGVN84M19F829Y', 'Viale dei Medici 104, 40100 Bologna', '3392468135', 'giovanni.ruggeri@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Francesca', 'De Luca', 'DLUFRN93B68M123P', 'Via della Repubblica 133, 89100 Reggio Calabria', '3452345678', 'francesca.deluca@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Riccardo', 'Desantis', 'DSTCRD81R11D510J', 'Piazza Torino 4, 10101 Torino', '3381234567', 'riccardo.desantis@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Eleonora', 'Rinaldi', 'RNLNLR94C62F205K', 'Piazza Venezia 107, 30100 Milano', '3399871234', 'eleonora.rinaldi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Fabio', 'Neri', 'NRIFFB86P07L219N', 'Via Romana 151, 9100 Cagliari', '3357654321', 'fabio.neri@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Stefania', 'Longo', 'LNGSFN90H58A123U', 'Corso Garibaldi 164, 90100 Roma', '3394567890', 'stefania.longo@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Michele', 'Giorgio', 'GRGMCZ87S30A123L', 'Via Verdi 104, 70101 Bari', '3386543210', 'michele.giorgio@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Giorgia', 'Fontana', 'FNTGRG95D55F839K', 'Viale Firenze 109, 50101 Firenze', '3467654321', 'giorgia.fontana@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Carlo', 'Riva', 'RVACRL83A03A321U', 'Corso XX Settembre 126, 20101 Milano', '3398765432', 'carlo.riva@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Laura', 'Martelli', 'MRTLRA94M69C657H', 'Via Dante 100, 89101 Catania', '3471234567', 'laura.martelli@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Daniele', 'Parisi', 'PRSDBL89R06H501H', 'Piazza del Popolo 77, 10102 Roma', '3352345678', 'daniele.parisi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Nicoletta', 'Serra', 'SRRNTT91E56H254O', 'Piazza Maggiore 192, 40101 Bologna', '3388765432', 'nicoletta.serra@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Alessandro', 'Clemente', 'CLMLSN85T22H501Z', 'Campo Santa Margherita 114, 30101 Venezia', '3394567890', 'alessandro.clemente@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Martina', 'De Santis', 'DSTMRT97C58L123J', 'Viale Europa 148, 95101 Catania', '3456789012', 'martina.desantis@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Roberto', 'Gallo', 'GLLRBT78M11H501K', 'Via Garibaldi 16, 70102 Bari', '3345678901', 'roberto.gallo@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Benedetta', 'Grassi', 'GRBNTT92B54L123Z', 'Viale dei Trastevere 38, 100 Roma', '3393456789', 'benedetta.grassi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Francesco', 'Pellegrini', 'PLLFRN84S10A910Z', 'Corso Sindaco 120, 20102 Milano', '3384567890', 'francesco.pellegrini@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Simona', 'Fumagalli', 'FMGSMN96H45F123X', 'Via delle Stelle 59, 10104 Torino', '3399876544', 'simona.fumagalli@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Luca', 'Marzano', 'MRZLCU83D17E123X', 'Viale della Libertà 88, 40102 Bologna', '3342345678', 'luca.marzano@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Giulia', 'Curatola', 'CRTGLA97E62B321L', 'Via dei Fiori 42, 50102 Firenze', '3467654321', 'giulia.curatola@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Mattia', 'Esposito', 'ESPMTT92A09D123H', 'Piazza della Stazione 101, 95102 Catania', '3356789012', 'mattia.esposito@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Valentina', 'Piazza', 'PZZVLT89L67H501T', 'Corso Roma 107, 20100 Milano', '3398765432', 'valentina.piazza@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Andrea', 'Bianchi', 'BNCNDR80C11H501F', 'Via della Libertà 26, 10101 Torino', '3351236789', 'andrea.bianchi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Silvia', 'Lucchini', 'LCHSLI88L42A321H', 'Viale della Repubblica 114, 95103 Catania', '3399877654', 'silvia.lucchini@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Mattia', 'Cattaneo', 'CTTNMT93S20H205F', 'Via di Porta 33, 50102 Firenze', '3467654321', 'mattia.cattaneo@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Giacomo', 'Moretti', 'MRTGCM85A08D512Q', 'Corso Nova 61, 10104 Torino', '3352345678', 'giacomo.moretti@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Roberta', 'Pinna', 'PNNRBT95E55A456Q', 'Viale Tiziano 147, 40103 Bologna', '3394566789', 'roberta.pinna@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Paolo', 'Battaglia', 'BTTPVL81M25H123P', 'Piazza della Libertà 2, 16100 Milano', '3456789012', 'paolo.battaglia@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Ilaria', 'De Marco', 'DMCRLR88E59H456F', 'Viale delle Alpi 155, 80100 Torino', '3352345678', 'ilaria.demario@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Claudio', 'Gatti', 'GTTCLD90H17D219X', 'Via Appia 100, 70100 Bari', '3466876543', 'claudio.gatti@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Aurora', 'Fabbri', 'FBBRRA93H54F123R', 'Viale delle Stelle 114, 9100 Cagliari', '3387654321', 'aurora.fabbri@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Fabio', 'Lucchesi', 'LCCFBI86T31H501S', 'Corso dei Banchi 158, 20104 Milano', '3352345678', 'fabio.lucchesi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Carla', 'Minelli', 'MNNCRL94B51H512L', 'Piazza Italia 95, 50103 Firenze', '3398765432', 'carla.minelli@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Nicolò', 'Fioravanti', 'FRVNLCD82C09H403B', 'Via delle Palme 78, 40100 Bologna', '3471234567', 'nicolo.fioravanti@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Claudia', 'Giorgio', 'GRGCLD90S62H900K', 'Viale Roma 183, 95104 Catania', '3345678976', 'claudia.giorgio@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Massimo', 'Mazzini', 'MZZMSM87L24D987R', 'Corso dei Martiri 163, 50100 Torino', '3324567820', 'massimo.mazzini@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Federica', 'Pietro', 'PTRFDR95R60B123C', 'Via Indipendenza 64, 20103 Milano', '3397654321', 'federica.pietro@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Giorgio', 'Rosa', 'RSRGHR80M07E123B', 'Viale dei Cittadini 114, 50104 Firenze', '3472345678', 'giorgio.rosa@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Alessia', 'Ravalli', 'RPLLSS83D52H401D', 'Via Roma 130, 10103 Torino', '3355678901', 'alessia.ravalli@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Stefano', 'Longhi', 'LNGSTF92L28H112Y', 'Piazza della Libertà 127, 70103 Bari', '3342345678', 'stefano.longhi@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Sara', 'Ricci', 'RCISRA96A47F987N', 'Corso dei Vittoria 162, 16101 Genova', '3398765432', 'sara.ricci@example.com');
INSERT INTO cliente (nomeCliente, cognomeCliente, cfCliente, indirizzoCliente, telCliente, emailCliente) VALUES ('Michele', 'Fabiani', 'FBMCHE79B19H501H', 'Viale degli Archi 74, 50101 Firenze', '3397656789', 'michele.fabiani@example.com');

-- Dump dei dati - tabella fornitore
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Pfizer', 'Via della Repubblica 150, 95101 Catania', 'pfizer@example.com', '3352345678');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Johnson&Johnson', 'Corso Manzon 23, 20101 Milano', 'johnsonandjohnson@example.com', '3467654321');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Roche', 'Piazza Garibaldi 16, 40104 Bologna', 'roche@example.com', '3398765432');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Novartis', 'Viale della Libertà 118, 10102 Torino', 'novartis@example.com', '3358768891');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Merck&Co', 'Corso di Porta 29, 50100 Firenze', 'merckandco@example.com', '3396655432');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('AstraZeneca', 'Via Sacra 163, 40102 Bologna', 'astrazeneca@example.com', '3345678901');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Sanofi', 'Via Argonauti 196, 101 Roma', 'sanofi@example.com', '3397654321');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('GlaxoSmithKline', 'Viale della Libertà 190, 10101 Torino', 'glaxosmithkline@example.com', '3355678901');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('Bayer', 'Corso Indipendenza 125, 95101 Catania', 'bayer@example.com', '3398765432');
INSERT INTO fornitore (nomeFornitore, indirizzoFornitore, emailFornitore, telFornitore) VALUES ('AbbVie', 'Viale Garibaldi 117, 20100 Milano', 'abbvie@example.com', '3341234567');

-- Dump dei dati - tabella prodotto
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Acetaminophen', '25', '8.19', '1', '1');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Acyclovir', '10', '6.95', '8', '10');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Alprazolam', '15', '5.43', '2', '6');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Benzalkonium Chloride', '15', '3.04', '4', '9');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Benzocaine', '5', '5.90', '1', '4');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Butalbital', '15', '7.62', '8', '4');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Candesartan', '25', '7.88', '7', '9');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Capsaicin', '20', '6.80', '1', '10');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Capsicum Chamomilla', '10', '6.54', '1', '2');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Cefoxitin', '10', '5.47', '2', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Citalopram', '10', '2.11', '9', '8');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Estazolam', '25', '2.91', '7', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Eucalyptol', '15', '6.06', '9', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Finasteride', '20', '7.50', '5', '2');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Galantamine', '15', '7.15', '9', '7');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Glipizide', '25', '6.40', '9', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Guaifenesin', '5', '2.21', '8', '7');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Hamster Epithelium', '20', '6.03', '3', '8');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Ibuprofen', '25', '3.24', '7', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Imipramine Hydrochloride', '15', '6.42', '2', '2');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Loratadine', '10', '2.24', '2', '10');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Lorazepam', '5', '2.00', '9', '9');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Menthol', '20', '2.55', '6', '2');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Metformin Hydrochloride', '20', '3.56', '2', '5');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Methylphenidate Hydrochloride', '20', '4.78', '4', '8');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Metronidazole', '15', '7.58', '1', '10');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Octinoxate', '10', '8.16', '7', '3');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Olanzapine', '10', '3.61', '8', '9');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Oxytocin', '25', '2.31', '5', '10');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Phenytoin', '25', '3.45', '10', '1');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Piperonyl butoxide', '20', '8.74', '10', '2');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Prednisone', '5', '7.59', '2', '5');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Pregabalin', '10', '6.30', '7', '8');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Risperidone', '20', '8.63', '8', '4');
INSERT INTO prodotto (nomeProdotto, pesoGrammi, prezzo, id_categoria, id_fornitore) VALUES ('Triclosan', '5', '3.35', '3', '5');

-- Dump dei dati - tabella ordine
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('41', '2025-01-01');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('26', '2025-01-01');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-01-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('22', '2025-01-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('34', '2025-01-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('28', '2025-01-03');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-01-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('23', '2025-01-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('45', '2025-01-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('29', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('23', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('10', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('12', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('17', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('28', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-01-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('18', '2025-01-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('40', '2025-01-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('42', '2025-01-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('48', '2025-01-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-01-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-01-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('27', '2025-01-13');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('36', '2025-01-14');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('39', '2025-01-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-01-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('17', '2025-01-16');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('36', '2025-01-16');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('21', '2025-01-16');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('47', '2025-01-17');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('36', '2025-01-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('26', '2025-01-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('15', '2025-01-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('28', '2025-01-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('4', '2025-01-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('2', '2025-01-21');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-01-21');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('46', '2025-01-22');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('42', '2025-01-22');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('5', '2025-01-23');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-01-24');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-01-26');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('20', '2025-01-26');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('19', '2025-01-27');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('39', '2025-01-27');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('49', '2025-01-28');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-01-28');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-01-28');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('38', '2025-01-29');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('27', '2025-01-29');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('5', '2025-01-29');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('19', '2025-02-01');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('50', '2025-02-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('43', '2025-02-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('39', '2025-02-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('36', '2025-02-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('42', '2025-02-04');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('17', '2025-02-04');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('41', '2025-02-04');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('4', '2025-02-04');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('11', '2025-02-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('48', '2025-02-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('9', '2025-02-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('49', '2025-02-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('18', '2025-02-06');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-07');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-02-07');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('9', '2025-02-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('31', '2025-02-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('46', '2025-02-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-02-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('48', '2025-02-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-11');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('47', '2025-02-11');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('35', '2025-02-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('35', '2025-02-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('12', '2025-02-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('10', '2025-02-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('39', '2025-02-14');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('28', '2025-02-14');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('38', '2025-02-14');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('40', '2025-02-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('26', '2025-02-16');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('9', '2025-02-16');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('50', '2025-02-17');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-17');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('23', '2025-02-17');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('7', '2025-02-18');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('4', '2025-02-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-02-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-02-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('15', '2025-02-19');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('24', '2025-02-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('26', '2025-02-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('50', '2025-02-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('18', '2025-02-21');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('23', '2025-02-22');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('21', '2025-02-24');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('16', '2025-02-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-02-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('13', '2025-02-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('49', '2025-02-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('13', '2025-02-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('27', '2025-02-26');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('40', '2025-02-27');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('37', '2025-03-01');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('41', '2025-03-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('27', '2025-03-02');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('22', '2025-03-03');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('49', '2025-03-03');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('10', '2025-03-04');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('4', '2025-03-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-03-05');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('31', '2025-03-07');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('34', '2025-03-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('11', '2025-03-08');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('8', '2025-03-09');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('22', '2025-03-09');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-03-09');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-03-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('21', '2025-03-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('35', '2025-03-10');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('29', '2025-03-11');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('2', '2025-03-11');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('12', '2025-03-11');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('15', '2025-03-12');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('25', '2025-03-13');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-03-14');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('19', '2025-03-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-03-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('22', '2025-03-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-03-15');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('15', '2025-03-17');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('3', '2025-03-18');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('35', '2025-03-20');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('4', '2025-03-21');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('43', '2025-03-21');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('22', '2025-03-22');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('47', '2025-03-22');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('14', '2025-03-23');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('33', '2025-03-24');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('30', '2025-03-25');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('37', '2025-03-27');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('41', '2025-03-28');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('34', '2025-03-29');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('32', '2025-03-29');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('45', '2025-03-30');
INSERT INTO ordine (id_cliente, dataOrdine) VALUES ('9', '2025-03-30');

-- Dump dei dati - tabella dettOrdine
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('1', '21', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('1', '15', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('1', '16', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('2', '16', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('2', '15', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('2', '12', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('3', '23', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('3', '32', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('3', '31', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('3', '12', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('4', '35', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('4', '4', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('4', '3', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('4', '14', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('4', '25', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('5', '19', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('5', '34', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('5', '2', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('6', '4', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('7', '27', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('7', '23', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('7', '14', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('8', '20', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('8', '5', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('9', '16', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('9', '23', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('9', '30', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('9', '10', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('10', '4', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('11', '1', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('11', '24', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('11', '5', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('12', '22', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('12', '13', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('13', '30', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('13', '31', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('14', '7', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('15', '21', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('15', '32', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('16', '28', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('17', '8', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('18', '12', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('18', '28', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('19', '23', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('19', '8', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('20', '17', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('20', '20', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('21', '14', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('22', '19', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('22', '7', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('22', '12', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('22', '22', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('23', '19', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('24', '19', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('24', '21', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('24', '5', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('25', '22', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('26', '6', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('27', '35', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('27', '9', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('28', '11', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('28', '29', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('28', '6', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('28', '16', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('28', '15', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('29', '9', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('30', '1', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('30', '17', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('30', '8', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('31', '22', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('31', '20', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('31', '18', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('31', '27', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('31', '12', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('32', '21', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('32', '14', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('33', '17', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('34', '9', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('34', '16', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('34', '7', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('35', '5', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('35', '20', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('35', '18', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('36', '26', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('36', '35', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('36', '13', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('37', '20', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('38', '5', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('39', '29', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('40', '15', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('41', '21', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('41', '7', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('41', '2', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('42', '28', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('42', '8', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('43', '21', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('43', '1', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('43', '31', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('44', '6', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('45', '3', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('46', '6', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('46', '19', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('46', '29', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('47', '8', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('48', '15', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('48', '32', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('48', '9', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('49', '24', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('49', '33', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('49', '28', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('49', '30', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('50', '17', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('50', '22', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('50', '23', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('50', '14', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('51', '21', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('51', '35', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('51', '14', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('52', '33', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('52', '3', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('53', '19', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('53', '28', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('53', '18', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('54', '25', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('54', '32', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('54', '19', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('54', '4', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('54', '20', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('55', '20', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('55', '22', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('55', '34', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('55', '35', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('56', '24', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('56', '14', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('56', '29', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('56', '11', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('57', '25', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('57', '20', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('57', '13', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('57', '2', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('57', '34', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('58', '16', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('58', '27', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('58', '20', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('58', '23', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('59', '31', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '16', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '28', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '2', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '13', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '33', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('60', '6', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('61', '9', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('62', '27', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('63', '27', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('63', '14', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('63', '29', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('63', '35', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('64', '26', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('65', '3', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('65', '4', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('66', '18', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('66', '26', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('66', '8', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('66', '33', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('67', '7', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('67', '3', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('67', '12', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('68', '2', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('68', '12', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('68', '30', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('69', '9', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('69', '14', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('69', '33', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('69', '8', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('70', '32', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('70', '13', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('70', '2', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('71', '16', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('71', '20', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('71', '25', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('71', '26', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('72', '14', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('72', '26', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('73', '22', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('73', '17', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('73', '16', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('74', '30', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('75', '18', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('75', '20', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('76', '18', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('77', '25', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('77', '15', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('77', '31', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('78', '26', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('79', '22', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('80', '14', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('80', '10', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('81', '12', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('81', '2', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('82', '26', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('82', '18', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('82', '27', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('83', '26', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('83', '19', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('84', '32', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('84', '21', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('84', '4', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '24', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '12', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '28', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '16', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '8', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('85', '23', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('86', '26', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('86', '22', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('86', '2', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('86', '25', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('87', '7', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('87', '35', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('87', '17', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('88', '18', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('88', '21', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('88', '16', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('88', '22', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('88', '34', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('89', '24', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('89', '15', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('90', '22', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('90', '17', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('90', '29', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '10', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '26', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '16', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '12', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '31', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('91', '13', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('92', '7', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('93', '8', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('93', '10', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('93', '2', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('93', '16', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('94', '32', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('94', '14', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('95', '3', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('95', '13', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('96', '16', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('96', '1', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('97', '19', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('97', '29', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('97', '27', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('98', '20', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('98', '35', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('99', '21', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('99', '25', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('99', '11', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('100', '22', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('100', '23', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('100', '12', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('100', '29', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('100', '26', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('101', '9', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('101', '25', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('101', '22', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('101', '26', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('102', '23', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('102', '32', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('102', '16', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('103', '12', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('103', '6', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('104', '4', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('105', '5', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('106', '24', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('106', '7', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('106', '22', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('106', '27', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('106', '34', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('107', '23', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('107', '29', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('107', '15', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('107', '17', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('108', '16', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('108', '24', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('108', '19', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('109', '31', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('109', '12', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('110', '27', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('111', '14', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('111', '24', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('111', '23', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('111', '4', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('112', '10', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('112', '28', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('112', '14', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('113', '19', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('114', '7', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('114', '17', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('115', '17', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('115', '4', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('116', '5', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('116', '1', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('117', '6', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('117', '33', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('117', '35', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('118', '6', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('118', '12', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('119', '25', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('119', '16', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('119', '7', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('119', '18', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '31', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '14', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '11', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '1', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '13', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '34', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('120', '24', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('121', '35', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('121', '29', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('122', '26', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('123', '33', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('123', '11', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('124', '9', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('124', '11', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('124', '33', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('125', '23', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('125', '16', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('125', '9', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('125', '19', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('126', '20', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('126', '34', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('126', '27', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('126', '33', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('127', '4', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('127', '29', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('128', '35', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('128', '19', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('128', '15', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('129', '35', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('129', '31', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('129', '25', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('130', '25', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('130', '1', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('131', '32', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('131', '29', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('131', '18', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('131', '17', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('132', '22', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('133', '30', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('133', '23', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('133', '31', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('133', '15', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('133', '13', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('134', '7', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('135', '16', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('135', '7', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('135', '25', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('135', '8', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('136', '31', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('136', '16', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('136', '19', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('136', '3', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('137', '14', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('138', '13', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('138', '33', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('138', '11', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('139', '24', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('140', '15', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('140', '4', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('140', '24', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('140', '29', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('141', '33', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('141', '24', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('141', '26', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('141', '18', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('141', '10', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('142', '16', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('142', '19', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('142', '3', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('142', '24', '3');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('143', '1', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('143', '32', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('144', '7', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('145', '8', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('145', '27', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('146', '26', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('146', '6', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('147', '2', '9');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('147', '11', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('148', '33', '2');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('148', '25', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('148', '1', '10');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('149', '34', '6');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('149', '27', '8');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('149', '9', '4');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('149', '8', '1');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('150', '29', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('150', '21', '7');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('150', '14', '5');
INSERT INTO dettOrdine (ID_ordine, ID_prodotto, quantitaProd) VALUES ('150', '8', '4');
