-- Database di PROFUMI

-- Creazione delle tabelle
CREATE TABLE brand (
  ID_brand INT AUTO_INCREMENT,
  nomeBrand VARCHAR(512),
  fondazioneBrand INT,
  descrizioneBrand VARCHAR(512),
  PRIMARY KEY (ID_brand)
);

CREATE TABLE naso (
  ID_naso INT AUTO_INCREMENT,
  nomeNaso VARCHAR(512),
  cognomeNaso VARCHAR(512),
  nascitaNaso INT,
  morteNaso INT,
  PRIMARY KEY (ID_naso)
);

CREATE TABLE profumo (
  ID_profumo INT AUTO_INCREMENT,
  nomeProfumo VARCHAR(512),
  id_brand INT,
  annoProfumo INT,
  genere VARCHAR(512),
  id_naso INT,
  topNotes VARCHAR(512),
  middleNotes VARCHAR(512),
  baseNotes VARCHAR(512),
  PRIMARY KEY (ID_profumo),
  FOREIGN KEY (id_brand) REFERENCES brand(ID_brand),
  FOREIGN KEY (id_naso) REFERENCES naso(ID_naso)
);

-- Dump dei dati - tabella brand
INSERT INTO brand (nomeBrand,fondazioneBrand,descrizioneBrand) VALUES
('Chanel',1909,'Chanel S.A. (/ʃaˈnɛl/) è una casa di moda parigina fondata all''inizio del ventesimo secolo da Coco Chanel. Specializzata nei beni di lusso (alta moda, prêt-à-porter, borse, profumeria e cosmetica, fra gli altri) il marchio Chanel è diventato uno dei più riconoscibili nomi nel campo della moda. La casa di moda è di proprietà dei fratelli Alain Wertheimer e Gerard Wertheimer, nipoti di Pierre Wertheimer, uno dei primi soci in affari di Coco Chanel.'),
('Christian Dior',1946,'Christian Dior SE (o più comunemente Dior) è una società europea (precedentemente francese come Christian Dior S.A.) specializzata nell''alta moda. Venne fondata da Christian Dior ed è di proprietà di Bernard Arnault, che è anche a capo di LVMH, il più grande gruppo di lusso al mondo. Dior detiene il 42% delle azioni e il 59% dei diritti di voto all''interno di LVMH.'),
('Editions de Parfums Frederic Malle',2000,'For Malle, there is only one rule perfumers have to follow when creating a perfume for the house: Eliminate all that is superfluous or merely decorative.'),
('Givenchy',1952,'Givenchy è un''azienda francese che produce capi di abbigliamento, accessori, profumi e cosmetici.'),
('Guerlain',1828,'Guerlain è una azienda francese, una delle più antiche aziende produttrici di profumi nel mondo. Fondata nel 1828 da Pierre François Pascal Guerlain, l''azienda è stata gestita dai membri della famiglia Guerlain fino al 1994, anno in cui è stata rilevata dal gruppo LVMH, multinazionale specializzata nei brand di lusso. Dal 1992 Jean Paul Guerlain è il direttore dell''azienda, nonché il principale profumiere. Jean Paul Guerlain infatti realizzava i profumi per l''azienda di famiglia già dagli anni cinquanta. '),
('Hermès',1837,'Hermès è un''azienda francese di moda (alta moda e prêt-à-porter, accessori, pelletteria, borse, arredamento, accessori per la casa, gioielli, profumi e valigie di lusso).'),
('Jean Patou',1914,'Patou, formerly known as Jean Patou or Jean Patou Paris, is a French fashion house.'),
('Yves Saint Laurent',1962,'Yves Saint Laurent (/iv sɛ̃ loˈʁɑ̃/) anche conosciuta come YSL, è una casa di moda francese fondata dallo stilista Yves Saint Laurent e dal suo partner, Pierre Bergé. Dal 2012 all''aprile 2016 direttore creativo del brand è stato Hedi Slimane, sostituito poi da Anthony Vaccarello.');

-- Dump dei dati - tabella naso
INSERT INTO naso (nomeNaso,cognomeNaso,nascitaNaso,morteNaso) VALUES
('Aimé','Guerlain',1846,1918),
('Alberto','Morillas',1950,NULL),
('Anne','Flipo',1969,NULL),
('Annick','Menardo',1958,NULL),
('Antoine','Lie',1974,NULL),
('Bernard','Bourgeois',1954,NULL),
('Bernard','Ellena',1954,NULL),
('Bertrand','Duchaufour',1969,NULL),
('Christine','Nagel',1958,NULL),
('Daniel','Molière',NULL,NULL),
('Dominique','Ropion',1955,NULL),
('Edmond','Roudnitska',1905,1992),
('Edouard','Flechier',1934,2007),
('Emilie','Coppermann',1977,NULL),
('Ernest','Beaux',1881,1961),
('François','Demachy',1959,NULL),
('Françoise','Donche',NULL,NULL),
('Guy','Robert',1926,2013),
('Henri','Alméras',1910,1986),
('Henri','Robert',1927,2007),
('Jacques','Cavallier',1962,NULL),
('Jacques','Guerlain',1874,1960),
('Jacques','Polge',1943,NULL),
('Jean','Carles',1892,1966),
('Jean','Kerleo',NULL,NULL),
('Jean Paul','Guerlain',1940,NULL),
('Jean-Claude','Ellena',1947,NULL),
('Jean-François','Latty',1966,NULL),
('Jean-Louis','Sieuzac',1954,NULL),
('Jean-Michel','Duriez',1964,NULL),
('Laurent','Bruyère',1969,NULL),
('Mark','Buxton',1964,NULL),
('Mathilde','Laurent',1970,NULL),
('Maurice','Roucel',1953,NULL),
('Michel','Gerard',1947,NULL),
('Michel','Roudnitska',1939,2013),
('Olivier','Cresp',1955,NULL),
('Olivier','Gillotin',1970,NULL),
('Olivier','Polge',1974,NULL),
('Paul','Lèger',NULL,NULL),
('Pierre','Bourdon',1947,NULL),
('Pierre-François-Pascal','Guerlain',1834,1910),
('Ralf','Schwieger',1967,NULL),
('Randa','Hammami',NULL,NULL),
('Thierry','Wasser',1960,NULL);

-- Dump dei dati - tabella profumo
INSERT INTO profumo (nomeProfumo,id_brand,annoProfumo,genere,id_naso,topNotes,middleNotes,baseNotes)
VALUES
('No. 5',1,1921,'Female',15,'Ylang-Ylang / Neroli / Aldehydes','Jasmine / Mayrose','Sandalwood / Vetiver'),
('No. 22',1,1922,'Female',15,'Aldehydes','Jasmine / Tuberose / Ylang-Ylang / Rose','Vetiver / Vanilla / Incense'),
('No. 19',1,1971,'Female',20,'Galbanum / Bergamot / Neroli / Hyacinth','Rose / Orris / Jasmine / Narcissus / Muguet / Ylang-Ylang','Musk / Sandal / Oakmoss / Leather / Cedarwood'),
('Cristalle Eau de Toilette',1,1974,'Female',20,'Sicilian Lemon / Bergamot','Rosewood / Hyacinth','Oakmoss / Vetiver'),
('Coco',1,1984,'Female',23,'Angelica / Mimosa / Frangipani / Mandarin','Cascarilla / Orange Flower / Bulgarian Rose / Jasmine','Labdanum / Ambrette Seed / Opopanax / Benzoin / Tonka / Vanilla'),
('Coco Mademoiselle',1,2001,'Female',23,'Orange / Bergamot / Grapefruit','Litchi / Rose / Italian Jasmine','Indonesian Patchouli / Haitian Vetiver / Bourbon Vanilla / White Musk'),
('Cristalle Eau de Parfum',1,1993,'Female',23,'Mandarin / Peach / Lily of the Valley / Sicilian Lemon / Bergamot','Jasmine / Iris / Rosewood / Hyacinth','Vetiver / Oakmoss'),
('Allure Homme',1,1999,'Male',23,'Bergamot / Mandarin / Citron Zest','Jamaican Pepper','Vetiver / Patchouli / Sandalwood / Cedarwood / Tonka Bean / Labdanum'),
('Antaeus',1,1981,'Male',23,'Clary Sage / Myrtle','Patchouli / Sandalwood','Labdanum / Beeswax Absolute'),
('Chanel Pour Monsieur',1,1955,'Male',20,'Neroli / Lemon / Petitgrain','Cardamom','Cedarwood / Oakmoss / Vetiver'),
('Chanel Pour Monsieur Concentrée',1,1989,'Male',23,'Mandarine / Lavender / Petitgrain','Cardamom / Nutmeg','Oakmoss / Vetiver / Opoponax / Vanilla'),
('Égoïste / L''Égoïste',1,1990,'Male',23,'Sicilian Tangerine / Brazilian Rosewood','Coriander / Damask Rose','Sandalwood / Vanilla / Ambrette seed'),
('Platinum Égoïste',1,1993,'Male',23,'Lavender / Rosemary / Petitgrain','Clary Sage / Geranium / Galbanum','Vetiver / Cedarwood / Labdanum / Treemoss'),
('Allure Homme Sport',1,2004,'Male',23,'Aldehydes / Mandarin / Orange / Aquatic Note','Black Pepper / Neroli / Cedar','Tonka / Vetiver / Amber / White Musk'),
('Allure Sensuelle',1,2005,'Female',23,'Bergamot / Mandarin Orange / Pink Pepper','Jasmine / Rose / Iris / Candied Fruit / Vetiver','French Vanilla / Amber / Patchouli / Frankincense / "Sensual Note"'),
('Chance Eau Fraîche',1,2007,'Female',23,'Citron / Water Hyacinth','Jasmine Absolute / White Musk','Vetiver / Amber / Patchouli / Teak'),
('Chance Eau Tendre',1,2010,'Female',23,'Grapefruit / Quince','Hyacinth / Jasmine','Amber / Cedar / Iris / White musk'),
('No. 19 Poudré',1,2011,'Female',23,'Mandarin / Neroli','Iris / Jasmine / Galbanum / Vetiver / Hyacinth','Musk / Tonka bean'),
('Coco Mademoiselle L''Extrait',1,2012,'Female',23,'Sicilian orange / Calabrian bergamot','May rose / Jasmine / Florentine iris','Patchouli / Vetiver / Bourbon vanilla / White musk'),
('Coco Noir',1,2012,'Female',23,'Grapefruit / Bergamot','Rose / Jasmine / Indonesian patchouli','Sandalwood / Brazilian Tonka bean / White musk'),
('1932',1,2013,'Female',23,'Aldehydes / Bergamot / Neroli','Jasmine / Rose / Lilac / Carnation / Ylang-ylang','Vetiver / Sandalwood / Opoponax / Orris root / Coumarin / Ambrette / Musk / Incense / Vanilla / Iralia'),
('Miss Dior',2,1947,'Female',24,'Galbanum','Jasmine','Patchouli'),
('Diorissimo',2,1956,'Female',12,'Muguet / Ylang-Ylang','Amaryllis / Boronia','Jasmine'),
('Dioressence',2,1969,'Female',18,'Violet / Rosebud','Geranium','Cinnamon / Patchouli'),
('Diorella',2,1972,'Female',12,'Sicilian Lemon / Peach / Asil / Italian Bergamot / Melon / Green Notes','Honeysuckle / Jasmine / Violet / Rose Bud / Carnation / Cyclamen / Oakmoss','Vanilla / Clove / Sandalwood / Vetiver / Musk / Patchouli'),
('Dolce Vita',2,1995,'Female',41,'Rose / Magnolia / Muguet','Apricot / Peach / Cinnamon','Sandalwood / Vanilla / Heliotrope'),
('Eau de Dolce Vita',2,1998,'Female',NULL,'Citrus notes / Pear blossom','Jasmine petals / Peony / Freesia / White Pepper','Sandalwood / Soft vanilla'),
('Hypnotic Poison',2,1998,'Female',4,'Caraway / Bitter Almond','Jasmine Sambac / Moss','Jacarander Wood / Vanilla / Musk'),
('Dune pour Homme',2,1997,'Male',37,'Fig Leaves / Basil Leaves / Blackcurrant Leaves / Mandarin','New Hedione / Moss / Sage','Fig tree wood / Sandalwood / Cedarwood / Tonka Bean'),
('Eau Sauvage',2,1966,'Male',12,'Lemon / Rosemary','Petitgrain / Basil','Vetiver'),
('Eau Sauvage Extrême',2,1982,'Male',NULL,'Lavender / Rosemary','Genista','Cedarwood / Cistus'),
('Fahrenheit',2,1988,'Male',29,'Hawthorn / Honeysuckle','Sandalwood','Lenstiscus / Styrax (Benzoin)'),
('Higher',2,2001,'Male',38,'Citrus notes / Basil / Pear','Spicy notes / Cypress / Rosemary flower','Pear tree wood / Musk'),
('Jules',2,1980,'Male',NULL,'Galbanum','Black Pepper','Cedarwood / Sandalwood / Russian Leather'),
('Fahrenheit 0 Degrés',2,2002,'Male',8,'Citrus','Violet / Freesia / Sandal','Patchouli / Cedar'),
('Higher Black',2,2002,'Male',38,'Citrus notes / Basil / Pear','Spicy notes / Cypress / Rosemary flower','Pear tree wood / Musk'),
('Dior Addict Eau Fraîche',2,2004,'Female',45,'Mandarin / Mandarin Leaf / Vanilla / Bergamot','Gardenia / Bulgarian Rose / Tuberose / Jasmine','Rosewood / Sandalwood'),
('Dior Addict "Dior Twist"',2,2006,'Female',NULL,'Ivy leaves / Freesia petals / Water jasmine','Rose / Almond blossoms / Geranium','Vanilla / Musk / Ambrette seeds'),
('Fahrenheit 32',2,2007,'Male',16,'Orange Blossom','Vetiver','Vanilla'),
('Midnight Poison',2,2007,'Female',NULL,'Bergamot / Orange','Rose','Patchouli / Amber'),
('Miss Dior Cherie Eau de Printemps',2,2008,'Female',NULL,'Blood Orange Essence / Calabrain Bergamot','Jasmine Absolute / Orange Blossom / Rose','Patchouli'),
('Bronze Sweet Sun',2,NULL,'Female',NULL,'Mandarin / Orange','Jasmine / Tiare flower','Ginger / Musk / Vanilla'),
('Hypnotic Poison Eau Sensuelle',2,2011,'Female',NULL,'Ylang-Ylang / Orange Blossom','Tuberose / Vanilla / Orchid','Sandalwood / Musk'),
('Granville',2,2010,'Unisex',16,'Lemon / Mandarin / Thyme','Rosemary / Pine / Gorse','Black Pepper / Sandalwood / Oakmoss'),
('Escale aux Marquises',2,2010,'Unisex',16,'Blood orange / Pink pepper / Cardamom / Pepper / Amalfi lemon / Tiare flower','Cinnamon / Ginger / Clove / Nutmeg / Coriander / Elemi resin','Benzoin / Vanilla'),
('Eau Sauvage Extrême (new / Intense)',2,2010,'Male',NULL,'Sicilian Lemon','Lavender of Vaucluse','Virginia Cedar'),
('Miss Dior Eau Fraîche',2,2012,'Female',16,'Bergamot / Fresh Notes','Gardenia / Floral Notes','Patchouli / Sweet Notes'),
('Aqua Fahrenheit',2,2011,'Male',16,'Citruses / tangerine / Grapefruit','Violet leaf / basil / Mint','Vetiver from Haiti / Leather'),
('Dior Addict to Life',2,2011,'Female',16,'Pomegranate / Raspberry / Peach','Rose / Jasmine / Lily of the valley','Cedar / White musk'),
('Eau Sauvage Parfum',2,2012,'Male',16,'Bergamot','Myrrh','Vetiver'),
('Escale a Parati',2,2012,'Unisex',16,'Bitter orange / Lemon / Petitgrain','Rosewood / Mint / Cinnamon / Red berries','Tonka bean / Woods'),
('Grand Bal',2,2012,'Female',16,'Bergamot / Jasmine','Ylang Ylang / Tunisian orange blossom','New Caledonia sandalwood / Musk'),
('Oud Ispahan',2,2012,'Unisex',16,'Labdanum','Indonesian Patchouli','Laotian Oud Essence / Turkish Rose / Sandalwood'),
('Dior Addict Eau Sensuelle',2,2012,'Female',16,'Rose','Jasmine','Musk / Cedar'),
('Miss Dior Le Parfum',2,2012,'Female',16,'Mandarin','Bulgarian rose / Turkish rose','Patchouli / Amber / Vanilla'),
('Hypnotic Poison Eau Secrète',2,2013,'Female',16,'Sicilian mandarin / Orange / Calabrian bergamot','Sambac jasmine / Tunisian neroli','Vanilla'),
('Miss Dior Eau De Toilette',2,2013,'Female',16,'Tunisian neroli','Bulgarian rose / Turkish rose','Indonesian patchouli'),
('Noir Epices',3,2000,'Unisex',36,'Orange / Rose / Geranium','Nutmeg / Cinnamon / Clove / Pepper','Patchouli / Cedarwood / Sandalwood'),
('Le Parfum de Thérèse',3,2000,'Female',12,'Mandarin / Melon / Jasmine / Pepper','Violet / Rose / Plum / Nutmeg','Cedar / Vetiver / Leather'),
('Iris Poudre',3,2000,'Unisex',41,'Bergamot / Orange / Rosewood / Ylang-Ylang / Carnation','Magnolia / Jasmine / Muguet / Vetta-Rose / Aldehydes','Iris / Musk / Amber / Vanilla / Sandalwood / Ebony'),
('Musc Ravageur',3,2000,'Unisex',34,'Lavender / Bergamot','Clove / Cinnamon','Gaiac wood / Cedar / Sandalwood / Vanilla / Ta / Musk'),
('Lys Méditerranée',3,2000,'Unisex',13,'Ginger Lily / Lily of the Valley (Muguet)','Angelica Root / Orange Flower / Water L','Musk'),
('Une Fleur de Cassie',3,2000,'Unisex',11,'Cassie / Mimosa / Jasmine / Clove / Cumin / Bergamot','Rose / Violet / Apricot / Ahyde / Salicylate /','Musk Cetone / Cedarwood / Sandalwood'),
('Dans Tes Bras',3,2008,'Female',34,'Bergamot / Clove / Violet / Jasmine','Sandalwood / Patchouli / Incense / Cashmeran','iotrope / White musk'),
('Géranium pour Monsieur',3,2009,'Male',11,'Mint / Pepper mint / Geranium / Rhodinol / Anethol / Floralzone','Cinnamon / Clove Oil','White Musk Cocktail / Ambroxan / Sandalwood / Incense / Syrax'),
('Eau de Givenchy',4,1980,'Female',NULL,'Bergamot / Spearmint / Fruity notes','Muguet / Jasmin / Rose / Cyclamen','Moss / Sandal / Cedar / Musk'),
('Extravagance D''Amarige',4,1998,'Female',35,'Green Mandarin / Tagete / Pink Peppercorn','Jasmine / Orange Blossom / Violet Leaves','Sandalwood / Cedarwood / Musk / Ambrox'),
('Givenchy Gentleman',4,1974,'Male',40,'Tarragon / Cinnamon','Patchouli / Vetiver','Civet / Russian Leather'),
('Insensé',4,1993,'Male',10,'Blackcurrant / Mandarin / Basil','Magnolia / Lily of the Valley / Iris / Lentiscus','Firbalsam'),
('Insensé Ultramarine',4,1994,'Male',NULL,'Water fruits / Galbanum','Cardamom / Mint Leaves','Cedar / Vetiver / Tobacco'),
('Monsieur de Givenchy',4,1959,'Male',NULL,'Hesperidian Notes','Lavender / Verbena','Oakmoss / Sandalwood'),
('Pi',4,1999,'Male',2,'Citrus / Aromatic / Green / Floral','Magnetic Wood','Benzoin Crystals'),
('Pi Fraiche',4,2001,'Male',2,'Tangerine / Jasmine /','Amber','Benzoin / Woody Notes'),
('Xeryus',4,1986,'Male',NULL,'Grapefruit / Artemisia','Cypress / Gaiac wood / Chinese Cypriol','Amber'),
('Xeryus Rouge',4,1995,'Male',4,'Kumquat / Cactus Flesh / Tarragon','Cedar Leaf / Red Pepper / African Geranium','Sandalwood / Cedar'),
('Givenchy pour Homme',4,2002,'Male',2,'Cool Grapefruit / Mandarin / Violet','Lush fruits / Exotic Spices / Floral notes','Warm woods / Vetiver'),
('Into the Blue',4,2002,'Unisex',32,'Winter Bergamot / Nettle Flower /','Sweet Pea / White Orchid','Luminous Woody Base'),
('Insensé Ultramarine Aromatic Ocean - Morning Surf',4,2002,'Male',NULL,'Citrus','Cinnamon','Sandalwood'),
('Insensé Ultramarine Aromatic Ocean - Evening Dream',4,2002,'Male',NULL,'Citrus','Cinnamon','Sandalwood'),
('Insensé Ultramarine Aromatic Ocean - Midnight Swim',4,2002,'Male',NULL,'Cinnamon','Cypress','Sandalwood'),
('Givenchy pour Homme Blue Label',4,2004,'Male',NULL,'Grapefruit / Hedione / Bergamot','Cardamom / Davana / Pepper','Olibanum / Vetiver / Cedar'),
('Eau Torride',4,2002,'Unisex',NULL,'Mandarin / Bergamot / Lemon','Jasmine','Sandalwood / Bamboo'),
('Ange ou Démon',4,2006,'Female',17,'White thyme / Mandarin  from Calabria and Essence of Saffron','Maxillaria orchid / Lily / Ylang ylang','Tonka bean / Vanilla / Rosewood / Oak wood absolute'),
('Pi Neo',4,2008,'Male',5,'Bergamot / Mandarin','Myrtle / Cedarwood','Patchouli'),
('Ange ou Démon Le Secret',4,2009,'Female',7,'Italian winter lemon / Cranberry / Green tea leaves','Sambac jasmine / White peony / Water flowers','Blond woods / Patchouli'),
('Play for Her',4,2010,'Female',14,'Pink peppercorns / White peach / Bergamot / Sweet pea','Amyris wood / Tiare flower / Magnolia leaf / Magnolia flower','Sandalwood / Musks'),
('Play Intense for Her',4,2010,'Female',14,'Pink peppercorns / Orange flower','Amyris wood / Tiare flower / Orchid','Sandalwood / Patchouli / Tonka bean'),
('Le Bouquet Absolu',4,2011,'Female',NULL,'Bergamot / Neroli / Wild berries','Jasmine / Vanilla orchid / Rose','Musk / Ambergris / Juniper'),
('Dahlia Noir',4,2011,'Female',NULL,'Pink pepper / Mandarin / Mimosa','Rose / Iris / Patchouli / Rose','Sandalwood / Vanilla / Tonka bean'),
('Very Irrésistible Givenchy Electric Rose',4,2012,'Female',NULL,'Blueberry / Lemon / Basil / Verbena','Rose / Anise / Green violet','Cedar / Musk'),
('Very Irrésistible L''Intense',4,2011,'Female',NULL,'Plum','Turkish Rose','Patchouli / White Musk'),
('Givenchy Play Sport',4,2012,'Male',NULL,'Bergamot / Ginger / Mint / Lemon leaf','Amirys wood / Pepper','Musk'),
('Ange ou Démon Tendre',4,2008,'Female',NULL,'Mandarin / Lily of the Valley / Orange Blossom','Lily / Peony / Heliotrope','Rosewood / Patchouli'),
('Very Irrésistible Tropical Paradise',4,2011,'Female',NULL,'Anise / Mint','Passion fruit / Rose','Sandalwood / Musk'),
('Givenchy Play Summer Vibrations',4,2010,'Male',NULL,'Coriander leaf / Citrus','Black pepper / Sea spray accord','Amyris wood'),
('Dahlia Noir Eau de Toilette',4,2012,'Female',16,'Mandarin / Peach / Lemon','Rose / Atlas Cedar / Pink pepper','Vanilla / Tonkin Musk / Ambergris / Sandalwood'),
('Eaudemoiselle de Givenchy Bois de Oud',4,2012,'Female',NULL,'Mandarin','Turkish rose / Orange blossom','Cedar / Olibanum / Amber / Vanilla / Oud'),
('Very Irrésistible Poesie d''un Parfum d''Hiver',4,2011,'Female',NULL,'Gingerbread / Honey / Candied orange','Star anise / Cinnamon / Rose','Vanilla'),
('Eaudemoiselle de Givenchy Eau Florale',4,2012,'Female',NULL,'Pear / Pink grapefruit','Japanese wild rose / Jasmine','Blonde woods / Musk'),
('Very Irrésistible Sensual',4,2005,'Female',11,'Peony','Rose / Star anise','Patchouli / Vanilla'),
('Gentlemen Only',4,2013,'Male',NULL,'Birch leaf / Green mandarin / Nutmeg / Pink pepper','Cedar / Patchouli / Vetiver','Animalic notes / Frankincense'),
('Dahlia Noir L''Eau',4,2013,'Female',16,'Citrus / Neroli','Rose','Patchouli / Cedar / Musk'),
('Bloom',4,2013,'Female',NULL,'Raspberry / Caviar','Iris / Violet / Tiare','Woods / Incense / Musk'),
('Après L''ondée',5,1906,'Female',22,'Aniseed / Hesperidic notes / Rose','Violet / Hawthorn','Iris root'),
('Mitsouko',5,1919,'Female',22,'Bergamot / Rose','Jasmin / Spices / Peach','Oakmoss / Woody notes'),
('L''Heure Bleue',5,1912,'Female',22,'Neroli','Carnation / Iris','Vanilla'),
('Liù',5,1929,'Female',22,'Aldehydes / Rose','Neroli / Jasmine / Rose','Iris / Woody notes / Vanilla'),
('Vol de Nuit',5,1933,'Female',22,'Hesperedic Notes / Narcissus','Galbanum / Oakmoss / Green notes','Wood / Iris / Vanilla / Spices'),
('Shalimar',5,1925,'Female',22,'Bergamot','Iris / Jasmine / Rose','Vanilla / Opoponax / Tonka bean'),
('Chant DArômes',5,1962,'Female',26,'Hesperidic notes / Honeysuckle','Gardenia / Jasmine / Ylang-ylang','Sandalwood / Oakmoss / Vanilla'),
('Chamade',5,1969,'Female',26,'Hyacinth / Jasmine','Ylang-Ylang / Blackcurrant bud / Galbanum','Vanilla / Woody notes / Balsamic notes'),
('Parure',5,1975,'Female',26,'Hesperidic notes / Plum','Rose / Jasmine / Lilac','Oakmoss / Spices / Wood'),
('Nahéma',5,1979,'Female',26,'Rose','Fruit','Vanilla / Wood'),
('Samsara',5,1989,'Female',26,'Jasmine / Ylang Ylang','Jasmine / Sandalwood / Narcissus','Tonka / Iris / Vanilla'),
('Petit Guerlain',5,1994,'Female',26,'Lavender / Hesperidic Notes','Mimosa / Jasmine / Rose','Tonka Bean'),
('Aqua Allegoria Flora Nerolia',5,2000,'Female',26,'Neroli / Petitgrain','Jasmine / Orange Blossom','Incense'),
('Metalys / Metallica',5,2000,'Female',26,'Vanilla','Ylang-Ylang / Orange Blossom / Carnation','Iris / Tonka Bean'),
('Mayotte / Mahora',5,2000,'Female',26,'Green and Fresh','Tuberose / Frangipani blossoms / Neroli / Ylang-Ylang / Jasmine','Vetiver / Vanilla / Sandalwood'),
('Philtre d''Amour',5,2000,'Female',26,'Lemon / Bergamot / Verbana','Jasmine / Petigrain / Neroli / Myrtle','Patchouli'),
('Aqua Allegoria Gentiana',5,2001,'Female',NULL,'Bergamot / Grapefruit / Limette / Lime','Bitter orange / Gentian / Pear','Vanilla / Musks'),
('Champs-Elysées',5,1904,'Female',22,'Mimosa Leaf / Almond Blossom / Rose','Buddleia / Mimosa Blossom','Almond Wood / Hibiscus / Hibiscus Seed'),
('Aqua Allegoria Herba Fresca',5,1999,'Unisex',33,'Clover Leaf / Italian Lemon','Spearmint / Green Tea','Lily of the Valley / Cyclamen / Pear Flower'),
('Aqua Allegoria Lavande Velours',5,1999,'Unisex',26,'Lavender','Lavender / Violet / Sandalwood','Woody / Irridescent Lavender'),
('Aqua Allegoria Pamplelune',5,1999,'Unisex',33,'Acidulous Grapefruit / Bergamot','Neroli / Petitgrain / Cassis','Patchouli / Vanilla'),
('Aqua Allegoria Winter Delice',5,2000,'Unisex',NULL,'Fir Trees','Scotch Pine / Balsam','Somalian Incense / Sugar and Vanilla'),
('Coriolan',5,1998,'Male',26,'Lemon tree leaves / Bergamot','Juniper / Absinthe / Coriander / Nutmeg / Juniper','Oakmoss / Patchouli / Everlasting flower'),
('Derby',5,1985,'Male',26,'Bergamot / Lemon / Artemisia / Peppermint','Pimento / Rose / Pepper / Mace / Jasmin','Leather / Vetiver / Sandal / Patchouli / Moss'),
('Eau de Guerlain',5,1974,'Unisex',26,'Lemon / Bergamot / Basil / Petitgrain / Caraway','Rose / Jasmin / Patchouli / Carnation / Sandal','Amber / Moss / Musk'),
('Eau de Cologne Impériale',5,1853,'Unisex',42,'Bergamot / Neroli / Verbena / Lemon / Orange','Lavender','Cedarwood / Tonka Bean'),
('Habit Rouge',5,1965,'Male',26,'Bergamot / Lemon / Rosewood / Basil / Pimento','Sandal / Carnation / Patchouli / Cedar / Rose / Cinnamon','Vanilla / Amber / Moss / Leather / Benzoin / Labdanum / Olibanum'),
('Héritage',5,1992,'Male',26,'Lemon / Lavender / Bergamot','Coriander / Pink peppercorn','Patchouli / Cerdarwood / Tonka beans / Vanilla'),
('Jicky',5,1889,'Unisex',1,'Lemon / Mandarin / Bergamot / Rosewood','Orris / Jasmin / Patchouli / Rose / Vetiver','Leather / Amber / Civet / Tonka / Incense / Benzoin'),
('Vetiver',5,1961,'Male',26,'Bergamot / Lemon / Mandarin / Neroli / Coriander','Vetiver / Cedar','Tobacco / Nutmeg / Pepper / Tonka bean / Capiscum'),
('Vetiver Eau Glacée',5,2004,'Male',26,'Lime / Orange / Bergamot','Neroli / Pepper / Nutmeg','Tonka / Vetiver'),
('Love is all',5,2005,'Female',NULL,'Mandarin / Pink pepper','Orange Blossom / Mimosa / Petals / Iris','Wood notes / Amber'),
('Lights of Champs-Élysées',5,2006,'Female',NULL,'Almond flower / Pink peppercorns','Mimosa / Iris wood / Ylang-ylang','Vetiver / Vanilla / Virginia Cedar'),
('Vetiver Extreme',5,2006,'Male',NULL,'Lemon / Bergamot / Artemisia','Olibanum / Pepper / Nutmeg','Tonka bean / Vétiver / Cedar'),
('L''Instant d''un Eté pour Homme',5,2006,'Male',NULL,'Neroli / Star Anise crystals / Yellow and green lemon / Grapefruit / Pink pepper / Elem','Patchouli / Cedarwood / Mysore Sandalwood','Bitter Cocoa Beans / Hibiscus seeds / Tea'),
('L''Instant d''un Eté',5,2006,'Female',NULL,'Grapefruit / Bitter Orange','Magnolia / Ylang-ylang / Sambac Jasmine','Vanilla / Benzoin / Musks / Amber'),
('Nuit d''Amour',5,2006,'Female',NULL,'Bay Rose / Aldehydes','May Rose / Iris','Powdery Notes / Sandalwood'),
('My Insolence',5,2007,'Female',NULL,'Raspberry','Almond Blossom / Jasmine','Patchouli / Vanilla / Tonka Bean'),
('Cruel Gardenia',5,2008,'Female',44,'Peach / Neroli / Damask Rose','Ylang-ylang / Gardenia / White Musk / Violet','Tonka Bean / Sandalwood'),
('Les Elixirs Charnels - Oriental Brûlant',5,2008,'Female',9,'White almond','Vanilla','Styrax / Tonka bean'),
('Les Secrets de Sophie',5,2009,'Female',26,'Petitgrain / Bigarade Orange / Tunisian Neroli / Bergamot','Orange Blossom / Jasmine / Violet leaves / Ylang-ylang','Tonka bean / Incense / Vanilla / White Musk'),
('Idylle',5,2009,'Female',45,'Lily of the valley / Lilac / Peony / Freesia / Jasmine','Bulgarian roses / Plessis robinson rose','Patchouli / White musk'),
('Arsène Lupin Dandy',5,2010,'Male',26,'Bergamot / Bigarade / Pink peppercorn / Cardamom','Sandalwood / Patchouli','Cistus / Olibanum'),
('Shalimar Parfum Initial',5,2011,'Female',45,'Bergamot / Orange / Green notes','Fruity notes / Rose / Jasmine / Iris','Patchouli / Vetiver / Vanilla / Tonka bean / White musk'),
('Une Ville, un Parfum : Moscow',5,2009,'Unisex',NULL,'Pine needles / Absinthe / Plum / Redcurrant / Bergamot / Lemon','Jasmine','Tonka bean / Sandalwood / Vanilla / White musk'),
('Une Ville, un Parfum : New York',5,2009,'Unisex',NULL,'Bergamot','Cinnamon / Cardamom','Cedar / Vanilla'),
('Une Ville, un Parfum : Tokyo',5,2009,'Unisex',NULL,'Green tea','Jasmine / Violet','Vanilla / Hinoki'),
('Une Ville, un Parfum : London',5,2011,'Unisex',NULL,'Bergamot / Rhubarb / Grapefruit','Cardamom / Rose / Violet','Vetiver / Black tea / White cedar'),
('Aqua Allegoria Flora Nymphéa',5,2010,'Female',45,'Citrus notes / Green accents / Wild Berries','Orange Blossom / Syringa / Honey','Wood / Musk'),
('Cherry Blossom Delight',5,2008,'Female',26,'Bergamot','Cherry Blossom','Green Tea'),
('L''Instant Magic Elixir',5,2009,'Female',NULL,'Bergamot / Flowery notes','Cedar / Sandalwood / Musk','Vanilla / Almonds'),
('Les Elixirs Charnels - Boisé Torride',5,2009,'Female',9,'Bergamot / Tangerine / Pink berries','Marshmallow / Orange blossom / Jasmine','Patchouli / White musk / Cedar'),
('Mon Precieux Nectar',5,2009,'Female',44,'Petitgrain / Bitter almond','Jasmine / Orange blossom','Woods / Incense / Vanilla / White musk'),
('Shalimar Ode à la Vanille',5,2010,'Female',45,'Lemon / Bergamot','Mayotte vanilla / Madagascar vanilla / rose / Jasmine / Iris','incense / Opoponax / Tonka bean'),
('Aqua Allegoria Jasminora',5,2011,'Female',45,'Galbanum / Bergamot','Cyclamen / Jasmine / Lily of the valley','Musk / Amber'),
('Myrrhe et Délires',5,2012,'Unisex',45,'Citrus / Pepper','Patchouli / Somalian myrrh / Iris / Violet / Peach / Rose / Jasmine','Musk / Woody amber / Frankincense'),
('Guerlain Homme L''Eau Boisée',5,2012,'Male',45,'Lime / Mint','Rum','Woods / Vetiver'),
('Habit Rouge LEau',5,2011,'Male',45,'Seville Orange / Hazelnut','Jasmine','Woody Notes / Vanilla'),
('Idylle Eau Sublime',5,2011,'Female',45,'Rosewater / Lychee','Rose / Jasmine / Peach','Patchouli / White Musk'),
('Shalimar Parfum Initial L''Eau',5,2012,'Female',45,'Orange / Bergamot / Grapefruit / Neroli','Damascena rose / Jasmine / Iris','Vanilla / Tonka bean'),
('Shalimar Parfum Initial L''Eau',5,2012,'Female',45,'Orange / Bergamot / Grapefruit / Neroli','Damascena rose / Jasmine / Iris','Vanilla / Tonka bean'),
('Les Elixirs Charnels - Floral Romantique',5,2011,'Female',45,'Mandarin / Orange / Jasmine','Ylang-ylang / Tiaré flower / Carnation / Lily','Cedar / Chestnut / Ambrette / Maté'),
('La Petite Robe Noire 2012',5,2012,'Female',45,'Black cherry / Bergamot / Red berries / Almond','Bulgarian rose / Turkish rose / Licorice / Smoked black tea','Aniseed / Tonka bean / Vanilla / Iris / Patchouli'),
('Eau de Shalimar',5,2008,'Female',26,'Orange / Bergamot / Lime','Rose / Jasmine','Vanilla / Iris / Resin'),
('Muguet 2012',5,2012,'Female',45,'Green Notes','Lilac / Lily of the Valley','Jasmine / Rose'),
('Les Déserts d''Orient - Encens Mythique d''Orient',5,2012,'Unisex',45,'Aldehydes / Rose / Saffron','Patchouli / Vetiver','Ambergris / Moss / Frankincense'),
('Les Déserts d''Orient - Rose Nacrée du Desert',5,2012,'Unisex',45,'Patchouli / Saffron','Cardamom / Curcuma / Oud','Benzoin / Myrrh'),
('Les Déserts d''Orient - Songe d''un Bois d''Été',5,2012,'Unisex',45,'Laurel / Neroli','Jasmine / Patchouli / Saffron / Cedar','Leather / Myrrh'),
('Le Bolshoï Saison 2012 La Traviata',5,2012,'Female',NULL,'Bergamot / Petitgrain / Orange / Neroli','Jasmine / Violet','Vanilla / Tonka bean / Incense / White musk'),
('La Petite Robe Noire Eau De Toilette',5,2013,'Female',45,'Rose / Jasmine / Orange blossom','Cherry / Apple / Blackcurrant / Green notes','White amber / Musk notes'),
('Amazone (original)',6,1974,'Female',NULL,'Bergamot / Geranium / Cassie / Hyacinth','Muguet / Orris / Rose / Jasmin','Cedarwood / Oakmoss / Vetiver / Amber'),
('Bel Ami',6,1986,'Male',NULL,'Lemon','Ylang-Ylang / Iris','Vanilla / Sandalwood / Vetiver'),
('Eau d''Orange Verte',6,1979,'Unisex',NULL,'Lemon / Mandarin','Papaya / Mango','Oakmoss / Patchouli'),
('Équipage',6,1970,'Male',18,'Rosewood / Bergamot / Lily of the Valley','Carnation / Jasmine / Pine','Tonka / Vetiver / Patchouli'),
('Rocabar',6,1998,'Male',6,'Juniper Berry / Cedar Needles / Lavender / Nutmeg / Cinnamon','Cypress / Atlas Cedar / Virginia Cedar','Basalm / Vanilla'),
('Eau des Merveilles',6,2004,'Female',43,'Vetiver / Oak / Cedar','Ambergris','Lemon / Orange / Elemi / Pink Pepper'),
('Un Jardin sur le  Nil',6,2005,'Unisex',27,'Green Mango / Grapefruit','Calamus / Lotus','Sycamore / Frankincense'),
('Terre d''Hermès Parfum',6,2009,'Male',27,'Grapefruit / Orange / Shiso','Flint accord','Woody notes'),
('Eau Claire des Merveilles',6,2010,'Female',27,'Citrus / Aldehydes','Floral notes / Spices','Vanilla / Powder / Driftwood'),
('Hermèssence Santal Massoïa',6,2011,'Unisex',27,'Green Fig','Sandalwood / Massoia bark / Coconut','Sandalwood / Vetiver'),
('Eau des Merveilles Au Bal des Etoiles',6,2012,'Female',27,'Bitter orange','Pepper / Oak','Ambergris / Amber'),
('Eau de Mandarine Ambrée',6,2013,'Unisex',27,'Mandarin','Passion fruit','Amber'),
('Joy',7,1930,'Female',19,'Aldehydes / Peach / Leafy Green','Rose / Jasmine / Ylang-Ylang / Tuberose','Sandalwood / Musk / Civet'),
('Enjoy',7,2003,'Female',30,'Cassis / Green Banana / Orange / Bergamot / Pear / Mandarin','Bulgarian Rose / Turkish Rose / Hedione / Indian Jasmine','Patchouli / Musk / Vanilla / Amber'),
('Patou pour Homme',7,1980,'Male',25,'Hot Pepper / Lavender / Tarragon / Black Pepper / Bergamot / Galbanum','Bourbon Vetiver / Cedar / Patchouli / Clary Sage','Oakmoss / Sandalwood / Mysore / Cistus Labdanum'),
('Voyageur',7,1994,'Male',25,'Grapefruit / Orange','Lavender / Sage','Cedarwood / Sandalwood / Oakmoss'),
('Sira des Indes',7,2006,'Female',30,'Banana accords / Bergamot / Pear / Pink berries / Cardamom','Floral notes','Musk / Amber / Vanilla / Sandalwood'),
('Eau de Patou pour Homme',7,1976,'Male',25,'Petitgrain / Orange / Sicilian lemon / Lime','Honeysuckle / Pepper / Tunisian orange blossom / Ylang ylang / Nasturcia','Amber / Musk / Civet / Oak moss'),
('Opium',8,1977,'Female',29,'Mandarin orange / Bergamot / Lily of the valley','Jasmine / Carnation / Myrrh','Vanilla / Patchouli / Opoponaux / Amber'),
('Baby Doll Paris',8,1999,'Female',43,'Grapefruit / Redcurrant / Rhubarb','Rose / Freesia / Spices','Peach / Grenadine / Cedarwood'),
('Nu Eau de Parfum',8,2001,'Female',21,'Bergamot','White Orchid / Black Pepper','Incense Absolut / Woody Notes / Spicy Notes / Vetiver'),
('Nu Eau de Toilette',8,2002,'Female',21,'Bergamot / Coriander','White Orchid / Jasmine Absolute','Incense'),
('Paris Premières Roses',8,2003,'Female',31,'Alba Rose Buds / Orange Blossom / Violet','Centiflora Rose / Muguet / Jasmine','Sandalwood / Vetiver / Musk'),
('Body Kouros',8,2000,'Male',4,'Incense / Eucalyptus','Cedarwood from China / Mace','Camphor wood / Benzoin'),
('Jazz',8,1988,'Male',28,'Artemisia / Lavender / Bergamot','Nutmeg / Geranium / Carnation / Cinnamon','Sandalwood / Cedarwood / Leather / Amber / Moss'),
('Jazz Prestige',8,1993,'Male',NULL,'Bergamot / Mint','Geranium / Apple','Sandalwood'),
('Kouros',8,1981,'Male',41,'Clove','Oakmoss','Incense'),
('Kouros Fraîcheur',8,1993,'Male',NULL,'Bergamot','Orange Blossom / Pineapple','Amber / Patchouli / Vetiver'),
('Live Jazz',8,1998,'Male',41,'Bitter Lemon Peel / Grapefruit / Iced Mint','Coriander / Wild Reed / Rhubarb Leaf','Cedarwood / Ambergris / Hint of Vanilla'),
('Opium pour Homme',8,1995,'Male',21,'Star Anise / Blackcurrant','Chinese Galanga / Szechuan Pepper','Bourbon Vanilla / Tolu Balm / Atlas Cedar'),
('YSL pour Homme',8,1971,'Male',NULL,'Lemon','Thyme','Vetiver'),
('M7',8,2002,'Male',2,'Bergamot / Mandarin / Rosemary','Vetiver / Agarwood','Amber / Musk / Mandrake root'),
('Kouros Cologne Sport',8,2003,'Male',NULL,'Frozen Cedrat / Bergamot / Tangerine / Citrus Notes','Jasmine / Cyclamen','Cedarwood / Ambergris'),
('Rive Gauche pour Homme',8,2003,'Male',21,'Bergamot / Star Anise / Rosemary','Lavender / Geranium Leaves / Cloves','Vetiver / Gaiac Wood / Patchouli'),
('Cinéma',8,2004,'Female',21,'Clementine / Almond Blossom / Cyclamen','Amarillys / Sambac jasmin / Peony','Amber / White musks / Bourbon vanilla / Benzoin'),
('Opium Fleur de Shanghai',8,2005,'Female',NULL,'Mandarin Orange','Magnolia / Star Jasmine / Carnation','Myrrh / Vanilla'),
('Paris Roses Enchantées',8,2005,'Female',NULL,'Garden Roses / Orange Blossom / Violets','Apricot Rose / Lilac Rose / Muguet','White musks / Sandalwood'),
('Paris Roses des Vergers Springtime',8,2006,'Female',NULL,'Cherry Blossom / Cyclamen / Black Currant Leaf','Pear Blossom / Tender Rose / Wild Rose','Musks / Sandalwood / Rhodes Wood'),
('Elle',8,2007,'Female',21,'Lychee / Citron / Peony','Jasmin sambac / Pink berries','Vetiver / Patchouli / Woody Notes'),
('Opium pour Homme Poésie de Chine Eau d''Orient',8,2008,'Male',NULL,'Grapefruit / Bergamot / Star anise','Orange blossom / Nutmeg / White pepper','Vetiver / Sandalwood / Amber'),
('Baby Doll Honeymoon',8,2009,'Female',NULL,'Passion fruit / Redcurrant / Rhubarb','Passion flower / Jasmine / Wild rose','Musk / Cedar wood'),
('Parisienne',8,2009,'Female',NULL,'Cranberry / Blackberry','Damask Rose / Violet / Peony / Leather','Patchouli / Vetyver / Musk / Sandalwood'),
('Elle Shocking',8,2007,'Female',NULL,'Mandarin / Ginger / Peony / Freesia / Jasmine','Floral notes / Raspberry','Musk / Cedar / Patchouli'),
('Parisienne L''Essentiel',8,2011,'Female',NULL,'Vinyl accord / Pink peppercorn / Blackberry','Damascan rose / Iris / Sambac jasmine','White leather accord / Tonka bean and musk'),
('L''Homme Libre',8,2011,'Male',39,'Calabria Bergamot / Nutmeg / Pink Pepper','Violet Leaf Accord / Grand Vert Basil / Star Anise','Indonesia Patchouli / Haiti Vetiver / Leather'),
('M7 Oud Absolu',8,2011,'Male',2,'Mandarin Orange / Mineral Notes','Oud / Patchouli','Rockrose / Myrrh / Amber Notes'),
('La Nuit de L''Homme Le Parfum',8,2010,'Male',NULL,'Bergamot / Anise / Pepper','Lavender / Labdanum / Fruity notes','Vetiver / Patchouli / Vanilla'),
('L''Homme Cologne Gingembre',8,2011,'Male',NULL,'Calabrian bergamot / Ozone aquatic accords','Chinese ginger / White pepper / Basil','Cedar / Oak moss / Vetiver / Musk'),
('Opium Vapeurs de Parfum',8,2012,'Female',NULL,'Mandarin / Pink pepper','Orange blossom / Jasmine','Incense / Amber / Nutmeg / Vanilla / Woods'),
('Parisienne L''Eau',8,2012,'Female',NULL,'Rose / Green freshness / Vinyl accord','Red fruits / Cranberry / Blackcurrant','Patchouli / White cedar / Musk'),
('La Nuit de L''Homme Frozen Cologne',8,2012,'Male',NULL,'Lemon / Mandarin / Bergamot / Frozen Cocktail Accord','Geranium / Pepper','Tonka Bean / Cashmere Wood / Vetiver / Cedar / Musk'),
('Paris Premières Roses 2012',8,2012,'Female',NULL,'Wild rose / Violet / Orange blossom','Peony / Lily of the valley / May rose','Sandalwood / White musk'),
('Manifesto',8,2012,'Female',3,'Bergamot / Cassis / Green Notes','Jasmin Sambac / Lily of the Valley','Sandalwood / Vanilla / Tonka Bean'),
('Elle Edition Limitée 2012',8,2012,'Female',NULL,'Mandarin / Grapefruit / Peony','Pink pepper / Raspberry / Sambac jasmine','Amber / Benzoin / Vetiver'),
('Parisienne à l''Extrême',8,2010,'Female',NULL,'Black elder','Damascus rose / Violet','Musk / Suede / Patchouli');
